"""
M4 Integration Module

This module coordinates the full quiz analysis workflow by
calling functions from M2 and M3.

Workflow:
1. Download raw respondent files
2. Collate raw respondent files
3. Generate statistics
4. Generate visualisations
"""

# Import required functions from other team modules

from data_preparation_M2 import (
    download_answer_files,
    collate_answer_files    
)

from data_analysis_M3 import (
    generate_means_sequence,
    visualize_data
)


def run_pipeline():
     """
    Runs the complete workflow from data download
    to analysis and visualisation.

    Returns
    -------
    None
    """
     
     # Cloud repository containing the raw answer files
     cloud_url = (
          "https://raw.githubusercontent.com/"
          "fc-leeds/MATH1604_2025_2026_data/main"
     )

     # Folder used to store downloaded raw files
     data_folder = "data"

     # Final collated output generated by M2
     collated_file = "output/collated_answers.txt"

     # Number of respondent files expected
     total_respondents = 64

     # ---------------- STEP 1 ----------------
     # Download all respondent files from GitHub
     print("Step 1: Downloading respondent files...")

     download_answer_files(
          cloud_url,
          data_folder,
          total_respondents
     )

     # ---------------- STEP 2 ----------------
     # Combine all raw respondent files into one file
     print("Step 2: Collating respondent files...")

     collate_answer_files(data_folder)

     # ---------------- STEP 3 ----------------
     # Generate the mean answer sequence
     print("Step 3: Generating statistics...")

     means = generate_means_sequence(
          collated_file
     )

     # Quick check so teammates can verify output
     print(
          "Successfully generated",
          len(means),
          "mean values."
     )

     print("First 10 means:")
     print(means[:10])

     # ---------------- STEP 4 ----------------
     # Display visualisations generated by M3
     print("Step 4: Generating visualisations...")

     # Scatter plot of means
     visualize_data(collated_file, 1)

     # Line plot of all respondent sequences
     visualize_data(collated_file, 2)

     print("Pipeline completed successfully.")

# Allow this file to be run independently
if __name__ == "__main__":

    run_pipeline()